version: '3.8'

services:
  # База данных
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5474:5432"
    environment:
      POSTGRES_USER: db1
      POSTGRES_PASSWORD: db1
      POSTGRES_DB: movies_platform_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - movies-network
    restart: unless-stopped

  # Kafka и Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - movies-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - movies-network

  # Eureka Server
  eureka-server:
    build: ./eurekaServer
    container_name: eureka-server
    ports:
      - "8774:8774"
    networks:
      - movies-network
    restart: on-failure

  # API Gateway
  api-gateway:
    build: ./apiGateway
    container_name: api-gateway
    ports:
      - "9074:9074"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_URI=http://eureka-server:8774/eureka/
    networks:
      - movies-network
    restart: on-failure

  # User Service
  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "8074:8074"
    depends_on:
      - postgres-db
      - kafka
      - eureka-server
      - api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/movies_platform_db
      - SPRING_DATASOURCE_USERNAME=db1
      - SPRING_DATASOURCE_PASSWORD=db1
      - KAFKA_SERVERS=kafka:9092
      - EUREKA_URI=http://eureka-server:8774/eureka/
      - API_GATEWAY_NAME=api-gateway
      - API_GATEWAY_PORT=9074
    networks:
      - movies-network
    restart: on-failure

  # Movie Service
  movie-service:
    build: ./movieservice
    container_name: movie-service
    ports:
      - "8075:8075"
    depends_on:
      - postgres-db
      - kafka
      - eureka-server
      - api-gateway
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/movies_platform_db
      - SPRING_DATASOURCE_USERNAME=db1
      - SPRING_DATASOURCE_PASSWORD=db1
      - KAFKA_SERVERS=kafka:9092
      - EUREKA_URI=http://eureka-server:8774/eureka/
      - API_GATEWAY_NAME=api-gateway
      - API_GATEWAY_PORT=9074
    networks:
      - movies-network
    restart: on-failure

networks:
  movies-network:
    name: movies-network

volumes:
  postgres-data:
    name: postgres-data